# Generated by Django 3.2.8 on 2021-10-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211020_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'Discounts'},
        ),
    ]
