# Generated by Django 3.2.8 on 2021-10-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211025_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_user',
            new_name='user_id',
        ),
    ]
